
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://rbwhqsdyagompvofmmrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid2hxc2R5YWdvbXB2b2ZtbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTMzOTUsImV4cCI6MjA1OTc4OTM5NX0.RNqMttUbJ8g2lKO0c50XzNt1EzUPmRvaXK5VdswX4G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
